name: Build

on:
  # Run this workflow for pushes on all branches
  push:
    branches:
      - '**'
  # Run this workflow when a tag or branch is created
  create:
  # Run this workflow for pull requests
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - version: 15.x
            option:
          - version: 16.x
            option:
          - version: 18.x
            option: --openssl-legacy-provider
          - version: 20.x
            option: --openssl-legacy-provider
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint files
      run: npm run lint:check
    - name: Build library
      run: npm run build
      env:
        NODE_OPTIONS: ${{ matrix.node-option }}
    - name: Run tests
      run: |
        npm install --no-save @vue/composition-api
        npm run test:unit
        npm prune @vue/composition-api
        npm prune --production
      env:
        NODE_OPTIONS: ${{ matrix.node-option }}

  build_and_publish_package:
    # Only run this job if the run_tests job has succeeded, and if
    # this workflow was triggered by the creation of a new tag
    needs: run_tests
    if: github.event_name == 'create' && github.event.ref_type == 'tag' && github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build
    - run: npm prune --production
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
